### ISSUE TITLE
SQL error while clicking view companies

### ISSUE THREAD

**Issue by saandeepatn** [prabh13/career_portal#5]
Go to Placements->View Companies->click any company
SQL error :
You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.$info['company_name'].'' AND req_year='2012'' at line 1

**Comment by rohitkumar79** [comment]
<td data-title="COMPANY"><a href="view_company_details.php?company='.$info['company_name'].'"><?php print $info['company_name'] ?></td>

change this in view_companies_php.php to

<td data-title="COMPANY"><a href="view_company_details.php"><?php print $info['company_name'] ?></td>

**Comment by prabh13** [comment]
relpace your line by:
<td data-title="COMPANY"><a href="view_company_details.php?company=<?php echo $info['company_name'];?>"><?php print $info['company_name'] ?></td>
